import { createServer } from 'node:http'
import { readFile } from 'node:fs/promises'
import { extname, join, normalize } from 'node:path'
import puppeteer from 'puppeteer-core'

const DIST = join(process.cwd(), 'dist')
const EDGE = 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'
const PORT = 4188
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.ttf': 'font/ttf', '.png': 'image/png', '.svg': 'image/svg+xml', '.json': 'application/json' }

const server = createServer(async (req, res) => {
  try {
    let p = decodeURIComponent((req.url || '/').split('?')[0])
    if (p === '/') p = '/index.html'
    const file = join(DIST, normalize(p))
    if (!file.startsWith(DIST)) throw new Error('escape')
    res.writeHead(200, { 'content-type': MIME[extname(file)] || 'application/octet-stream' })
    res.end(await readFile(file))
  } catch {
    res.writeHead(404)
    res.end('nf')
  }
})
await new Promise((r) => server.listen(PORT, r))
const browser = await puppeteer.launch({ executablePath: EDGE, headless: 'new', args: ['--no-sandbox', '--disable-gpu'] })
const page = await browser.newPage()
await page.setViewport({ width: 420, height: 800 })
page.on('console', (m) => console.log('[console]', m.type(), m.text().slice(0, 300)))
page.on('pageerror', (e) => console.log('[pageerror]', String(e).slice(0, 600)))
await page.goto(`http://localhost:${PORT}/`, { waitUntil: 'networkidle0' })
await new Promise((r) => setTimeout(r, 1500))
await new Promise((r) => setTimeout(r, 2500))
const splashGone = await page.evaluate(() => !document.getElementById("splash"))
const appHtml = await page.evaluate(() => (document.getElementById("app") || {}).innerHTML || "NO APP")
console.log("[splash gone]", splashGone)
console.log("[app]", appHtml.replace(/\s+/g, " ").slice(0, 500))
const hasHero = await page.evaluate(() => !!document.querySelector(".nt-hero"))
console.log("[today hero rendered]", hasHero)
const heroSubject = await page.evaluate(() => document.querySelector(".nt-hero .subject")?.textContent || "NO HERO")
console.log("[hero subject]", heroSubject)
const taskRows = await page.evaluate(() => document.querySelectorAll(".taskrow").length)
console.log("[task rows]", taskRows)
await page.keyboard.press('3')
await new Promise((r) => setTimeout(r, 500))
console.log("[after 3]", await page.evaluate(() => document.querySelector('.nt-pagehead h1')?.textContent))
await page.keyboard.press('5')
await new Promise((r) => setTimeout(r, 500))
console.log("[after 5]", await page.evaluate(() => document.querySelector('.nt-pagehead h1')?.textContent))
await page.keyboard.press('1')
await new Promise((r) => setTimeout(r, 800))
console.log("[after 1]", await page.evaluate(() => document.querySelector('.nt-pagehead h1')?.textContent))
console.log("[hero after 1]", await page.evaluate(() => !!document.querySelector('.nt-hero')))
const before = await page.evaluate(() => localStorage.getItem('ese_planner_checked_v3'))
await page.click('.taskrow .task-toggle')
await new Promise((r) => setTimeout(r, 300))
const after = await page.evaluate(() => localStorage.getItem('ese_planner_checked_v3'))
console.log("[checked before]", before, "[after toggle]", after)
await page.keyboard.press('z')
await new Promise((r) => setTimeout(r, 500))
const undid = await page.evaluate(() => localStorage.getItem('ese_planner_checked_v3'))
console.log("[after z]", undid, "[equals before]", undid === before)
const q1 = await page.evaluate(() => document.querySelector('.nt-whisper .q')?.textContent)
await page.click('.nt-whisper')
await new Promise((r) => setTimeout(r, 400))
const q2 = await page.evaluate(() => document.querySelector('.nt-whisper .q')?.textContent)
console.log("[quote before]", q1?.slice(0, 30), "[after]", q2?.slice(0, 30))
console.log("[quote idx key]", await page.evaluate(() => localStorage.getItem('ese_quote_idx')))
console.log("[nt-greet present]", await page.evaluate(() => !!document.querySelector('.nt-greet')))
console.log("[current screen]", await page.evaluate(() => document.querySelector('.screen .nt-pagehead h1')?.textContent || (document.querySelector('.screen')?.className || 'NO SCREEN')))
await page.keyboard.press('3')
await new Promise((r) => setTimeout(r, 400))
console.log("[focus mounted]", await page.evaluate(() => !!document.querySelector('.nt-fclock')))
const pomoBefore2 = await page.evaluate(() => localStorage.getItem('ese_planner_pomo_v5'))
await page.$eval('.fkey.run', (el) => el.click())
await new Promise((r) => setTimeout(r, 700))
const pomoAfter2 = await page.evaluate(() => localStorage.getItem('ese_planner_pomo_v5'))
console.log("[pomo before]", pomoBefore2)
console.log("[pomo after]", pomoAfter2)
console.log("[big]", await page.evaluate(() => document.querySelector('.nt-fclock .big')?.textContent))
await page.keyboard.press('3')
await new Promise((r) => setTimeout(r, 300))
await page.$eval('.nt-floop', (el) => el.click())
await new Promise((r) => setTimeout(r, 400))
console.log("[after loop click]", await page.evaluate(() => localStorage.getItem('ese_planner_pomo_v5')))
console.log("[loop el class]", await page.evaluate(() => document.querySelector('.nt-floop')?.className))
await page.keyboard.press('4')
await new Promise((r) => setTimeout(r, 500))
console.log("[progress phead]", await page.evaluate(() => !!document.querySelector('.nt-phead .pbig')))
console.log("[progress pbig]", await page.evaluate(() => document.querySelector('.nt-phead .pbig')?.textContent))
console.log("[progress cells]", await page.evaluate(() => document.querySelectorAll('.nt-pgrid .pcell').length))
console.log("[progress streaks]", await page.evaluate(() => document.querySelectorAll('.nt-pstreak .pstk').length))
console.log("[progress achs]", await page.evaluate(() => document.querySelectorAll('.nt-achgrid .achwrap').length))
console.log("[progress heat]", await page.evaluate(() => document.querySelectorAll('.heatgrid .hcell').length))
console.log("[progress bars]", await page.evaluate(() => document.querySelectorAll('.barrow .barcol').length))
console.log("[progress quality]", await page.evaluate(() => !!document.querySelector('.qrow')))
console.log("[progress habits rows]", await page.evaluate(() => document.querySelectorAll('.hbt-row').length))
console.log("[progress subj]", await page.evaluate(() => document.querySelectorAll('.subjlist .subj').length))
console.log("[progress errors]", await page.evaluate(() => window.__errCount || 0))

await browser.close()
server.close()